from flask import Flask, Response, jsonify, render_template_string
from flask_cors import CORS
import json
import os
from datetime import datetime


app = Flask(__name__)

CORS(
    app,
    resources={
        r"/api/*": {
            "origins": [
                "http://127.0.0.1:3000",
                "http://localhost:3000",
                "http://127.0.0.1:3001",
                "http://localhost:3001",
                "http://192.168.74.131:3000",
                "http://192.168.74.131:3001",
            ]
        }
    }
)

# ============================================================
# PROJECT PATHS
# ============================================================

PROJECT_ROOT = os.path.dirname(
    os.path.abspath(__file__)
)

LOG_FILE = os.path.join(
    PROJECT_ROOT,
    "logs",
    "events.jsonl"
)


# ============================================================
# EVENT READER
# ============================================================

def read_events():
    """
    Read Common Events from the persistent JSONL log.

    Invalid JSON lines are ignored so that one malformed
    record does not break the dashboard.
    """

    events = []

    if not os.path.exists(LOG_FILE):
        return events

    try:

        with open(
            LOG_FILE,
            "r",
            encoding="utf-8"
        ) as file:

            for line in file:

                line = line.strip()

                if not line:
                    continue

                try:

                    event = json.loads(line)

                    if isinstance(event, dict):
                        events.append(event)

                except json.JSONDecodeError:
                    continue

    except OSError:
        pass

    return events


# ============================================================
# HELPERS
# ============================================================

def events_by_source(events, source):
    """
    Return events belonging to a specific monitor/source.
    """

    return [
        event
        for event in events
        if event.get("source") == source
    ]


def latest_events(events, limit=20):
    """
    Return newest events first.
    """

    return list(reversed(events[-limit:]))


def calculate_risk(events):
    """
    Dashboard-level risk summary.

    Detection events generated by the detection engine
    are treated as high-risk indicators.

    This endpoint does NOT replace core/risk_engine.py.
    The core risk engine remains authoritative for actual
    project risk decisions.
    """

    detection_events = events_by_source(
        events,
        "detection_engine"
    )

    if detection_events:

        latest_detection = detection_events[-1]

        data = latest_detection.get(
            "data",
            {}
        )

        risk = data.get(
            "risk",
            "HIGH"
        )

        return {
            "risk_level": risk,
            "reason": (
                latest_detection.get("indicator")
                or latest_detection.get("event_type")
                or "Suspicious behavior detected."
            ),
            "signals": [
                latest_detection.get("indicator")
            ]
            if latest_detection.get("indicator")
            else [],
            "detected": True,
            "timestamp": latest_detection.get(
                "timestamp"
            )
        }

    return {
        "risk_level": "NORMAL",
        "reason": (
            "No currently implemented "
            "high-risk behavioral activity detected."
        ),
        "signals": [],
        "detected": False,
        "timestamp": None
    }


def build_process_summary(events):
    """
    Build a lightweight process view from process-monitor
    events and network/process attribution.

    This does not claim that a process is currently alive
    unless the event itself represents observed activity.
    """

    process_events = events_by_source(
        events,
        "process_monitor"
    )

    processes = {}

    for event in process_events:

        pid = event.get("pid")

        if pid is None:
            continue

        processes[pid] = {
            "pid": pid,
            "name": event.get("process"),
            "event_type": event.get("event_type"),
            "indicator": event.get("indicator"),
            "timestamp": event.get("timestamp"),
            "data": event.get("data", {})
        }

    return list(
        reversed(
            list(processes.values())
        )
    )


def build_file_summary(events):
    """
    Build a file-activity view from file monitor events.
    """

    file_events = events_by_source(
        events,
        "file_monitor"
    )

    result = []

    for event in reversed(file_events[-100:]):

        data = event.get(
            "data",
            {}
        )

        operation = event.get(
            "event_type",
            "unknown"
        )

        path = (
            data.get("path")
            or data.get("to")
            or data.get("from")
        )

        result.append({
            "id": (
                f'{event.get("timestamp", "")}-'
                f'{event.get("pid", "none")}-'
                f'{len(result)}'
            ),
            "timestamp": event.get(
                "timestamp"
            ),
            "operation": operation,
            "path": path,
            "pid": event.get("pid"),
            "process": event.get("process"),
            "indicator": event.get(
                "indicator"
            ),
            "data": data
        })

    return result


def build_network_summary(events):
    """
    Build a network-activity view from network-monitor
    events.
    """

    network_events = events_by_source(
        events,
        "network_monitor"
    )

    result = []

    for event in reversed(network_events[-100:]):

        data = event.get(
            "data",
            {}
        )

        result.append({
            "timestamp": event.get(
                "timestamp"
            ),
            "pid": event.get(
                "pid"
            ),
            "process": event.get(
                "process"
            ),
            "indicator": event.get(
                "indicator"
            ),
            "local_address": data.get(
                "local_address"
            ),
            "remote_address": data.get(
                "remote_address"
            ),
            "status": data.get(
                "status"
            ),
            "data": data
        })

    return result


# ============================================================
# ROUTES
# ============================================================

@app.route("/")
def dashboard():
    """
    Keep the old Flask dashboard available.

    The new React SOC frontend runs separately on port 3000.
    """

    return render_template_string(
        """
        <!DOCTYPE html>
        <html>
        <head>
            <title>Ransomware Defense API</title>
            <style>
                body {
                    background: #10131a;
                    color: #e1e2ec;
                    font-family: monospace;
                    padding: 40px;
                }
                h1 {
                    color: #ffb4ab;
                }
                li {
                    margin: 12px 0;
                }
                code {
                    color: #9ecaff;
                }
            </style>
        </head>
        <body>

            <h1>RANSOMWARE DEFENSE // BACKEND API</h1>

            <p>
                Backend is running.
            </p>

            <h2>Available endpoints</h2>

            <ul>
                <li><code>/api/status</code></li>
                <li><code>/api/events</code></li>
                <li><code>/api/network</code></li>
                <li><code>/api/processes</code></li>
                <li><code>/api/files</code></li>
                <li><code>/api/risk</code></li>
            </ul>

            <p>
                React SOC frontend:
                <code>http://127.0.0.1:3000</code>
            </p>

        </body>
        </html>
        """
    )


@app.route("/favicon.ico")
def favicon():

    return Response(
        status=204
    )


# ============================================================
# STATUS API
# ============================================================

@app.route("/api/status")
def api_status():

    events = read_events()

    file_events = events_by_source(
        events,
        "file_monitor"
    )

    network_events = events_by_source(
        events,
        "network_monitor"
    )

    process_events = events_by_source(
        events,
        "process_monitor"
    )

    detection_events = events_by_source(
        events,
        "detection_engine"
    )

    risk = calculate_risk(events)

    return jsonify({

        "status": "ONLINE",

        "monitoring": True,

        "safe_lab_mode": True,

        "protection_mode": "DRY_RUN",

        "event_count": len(events),

        "file_event_count":
            len(file_events),

        "network_event_count":
            len(network_events),

        "process_event_count":
            len(process_events),

        "detection_event_count":
            len(detection_events),

        "risk_level":
            risk["risk_level"],

        "risk_reason":
            risk["reason"],

        "timestamp":
            datetime.now().isoformat(
                timespec="seconds"
            )

    })


# ============================================================
# EVENTS API
# ============================================================

@app.route("/api/events")
def api_events():

    events = read_events()

    file_events = events_by_source(
        events,
        "file_monitor"
    )

    network_events = events_by_source(
        events,
        "network_monitor"
    )

    detection_events = events_by_source(
        events,
        "detection_engine"
    )

    risk = calculate_risk(events)

    return jsonify({

        "total_events":
            len(events),

        "file_events":
            len(file_events),

        "network_events":
            len(network_events),

        "alerts":
            len(detection_events),

        "risk":
            risk["risk_level"],

        "reason":
            risk["reason"],

        "signals":
            risk["signals"],

        "recent_events":
            latest_events(
                events,
                50
            ),

        "network_events_list":
            latest_events(
                network_events,
                20
            ),

        "file_events_list":
            latest_events(
                file_events,
                20
            ),

        "detection_events_list":
            latest_events(
                detection_events,
                20
            )

    })


# ============================================================
# NETWORK API
# ============================================================

@app.route("/api/network")
def api_network():

    events = read_events()

    network_events = build_network_summary(
        events
    )

    repeated_events = [
        event
        for event in events
        if (
            event.get("event_type")
            == "repeated_network_activity"
        )
    ]

    return jsonify({

        "count":
            len(network_events),

        "connections":
            network_events,

        "repeated_activity":
            latest_events(
                repeated_events,
                20
            )

    })


# ============================================================
# PROCESS API
# ============================================================

@app.route("/api/processes")
def api_processes():

    events = read_events()

    processes = build_process_summary(
        events
    )

    return jsonify({

        "count":
            len(processes),

        "processes":
            processes

    })


# ============================================================
# FILE API
# ============================================================

@app.route("/api/files")
def api_files():

    events = read_events()

    files = build_file_summary(
        events
    )

    return jsonify({

        "count":
            len(files),

        "files":
            files

    })


# ============================================================
# RISK API
# ============================================================

@app.route("/api/risk")
def api_risk():

    events = read_events()

    risk = calculate_risk(
        events
    )

    return jsonify(risk)


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":

    print()
    print(
        "=========================================="
    )
    print(
        " RANSOMWARE DEFENSE // BACKEND API"
    )
    print(
        "=========================================="
    )
    print()

    print(
        "API:"
        " http://127.0.0.1:5000"
    )

    print()

    print(
        "Event source:"
    )

    print(
        LOG_FILE
    )

    print()

    print(
        "Mode: SAFE / DRY-RUN"
    )

    print()

    print(
        "Press Ctrl+C to stop."
    )

    print()

    app.run(
        host="0.0.0.0",
        port=5000,
        debug=False
    )
