import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  useCallback,
} from 'react';

import {
  TabType,
  SocEvent,
  NetworkConnection,
  ProcessItem,
  FileActivityItem,
  BehavioralTelemetry,
  SystemStatus,
} from '../types';


/*
 * ============================================================
 * REAL BACKEND CONFIGURATION
 * ============================================================
 *
 * React/Vite:
 *     http://127.0.0.1:3000
 *
 * Flask:
 *     http://127.0.0.1:5000
 *
 * The dashboard receives telemetry from Flask.
 * Flask reads the real events.jsonl generated by the
 * ransomware-lab monitors.
 */

const API_BASE =
  import.meta.env.VITE_API_BASE_URL ||
  'http://192.168.74.131:5000';


/*
 * ============================================================
 * CONTEXT CONTRACT
 * ============================================================
 */

interface SocContextType {
  activeTab: TabType;
  setActiveTab: (tab: TabType) => void;

  systemStatus: SystemStatus;
  setSystemStatus: React.Dispatch<
    React.SetStateAction<SystemStatus>
  >;

  events: SocEvent[];

  addEvent: (
    event: Omit<SocEvent, 'id'>
  ) => void;

  clearEvents: () => void;

  toggleStream: () => void;

  connections: NetworkConnection[];

  processes: ProcessItem[];

  selectedProcess: ProcessItem | null;

  setSelectedProcess: (
    process: ProcessItem | null
  ) => void;

  fileActivities: FileActivityItem[];

  behavioralTelemetry: BehavioralTelemetry;

  actionLogs: string[];

  triggerContainment: () => void;

  restoreHost: () => void;

  killProcess: (
    pid: number
  ) => void;

  toggleSafeLabMode: () => void;

  simulateAttack: () => void;

  resetSimulation: () => void;

  currentTimeString: string;
}


const SocContext =
  createContext<SocContextType | undefined>(
    undefined
  );


/*
 * ============================================================
 * GENERIC HELPERS
 * ============================================================
 */

function makeEventId(
  event: any,
  index: number
): string {

  return [
    event?.timestamp || 'event',
    event?.pid ?? 'none',
    event?.event_type || 'unknown',
    index,
  ].join('-');
}


function formatTime(
  timestamp: string | undefined
): string {

  if (!timestamp) {
    return '--:--:--';
  }

  try {

    const date =
      new Date(timestamp);

    if (Number.isNaN(
      date.getTime()
    )) {
      return timestamp;
    }

    return date
      .toISOString()
      .substring(11, 23);

  } catch {

    return timestamp;
  }
}


function getSeverity(
  event: any
): string {

  const source =
    event?.source || '';

  const type =
    event?.event_type || '';

  const indicator =
    event?.indicator || '';

  const text = (
    `${source} ${type} ${indicator}`
  ).toLowerCase();


  if (
    source === 'detection_engine' ||
    text.includes('critical') ||
    text.includes('ransomware')
  ) {
    return 'critical';
  }


  if (
    text.includes('suspicious') ||
    text.includes('repeated') ||
    text.includes('deletion') ||
    text.includes('rename')
  ) {
    return 'high';
  }


  if (
    source === 'network_monitor'
  ) {
    return 'medium';
  }


  return 'info';
}


function getSourceLabel(
  source: string | undefined
): string {

  switch (source) {

    case 'file_monitor':
      return 'FILE MONITOR';

    case 'process_monitor':
      return 'PROCESS MONITOR';

    case 'network_monitor':
      return 'NETWORK MONITOR';

    case 'detection_engine':
      return 'DETECTION ENGINE';

    default:
      return (
        source || 'SYSTEM'
      ).toUpperCase();
  }
}


/*
 * ============================================================
 * EVENT MAPPING
 * ============================================================
 */

function mapEvent(
  event: any,
  index: number
): SocEvent {

  const data =
    event?.data || {};

  const path =
    data.path ||
    data.to ||
    data.from;


  return {
    id: makeEventId(
      event,
      index
    ),

    time: formatTime(
      event?.timestamp
    ),

    source: getSourceLabel(
      event?.source
    ),

    event:
      event?.event_type ||
      'unknown_event',

    indicator:
      event?.indicator ||
      '-',

    pid:
      event?.pid ??
      undefined,

    process:
      event?.process ||
      'Unknown',

    sev:
      getSeverity(event) as any,

    path,

    entropy:
      data.entropy ??
      undefined,

  } as SocEvent;
}


/*
 * ============================================================
 * NETWORK MAPPING
 * ============================================================
 */

function mapNetwork(
  event: any,
  index: number
): NetworkConnection {

  const data =
    event?.data || {};


  const remote =
    data.remote_address ||
    '-';

  const local =
    data.local_address ||
    '-';


  let indicator =
    'NORMAL';


  if (
    event?.event_type ===
    'repeated_network_activity'
  ) {
    indicator =
      'SUSPICIOUS';
  }


  return {

    id:
      `net-${makeEventId(
        event,
        index
      )}`,

    time:
      formatTime(
        event?.timestamp
      ),

    process:
      event?.process ||
      'Unknown',

    pid:
      event?.pid ??
      0,

    localAddress:
      local,

    remoteAddress:
      remote,

    status:
      data.status ||
      'UNKNOWN',

    indicator,

  } as NetworkConnection;
}


/*
 * ============================================================
 * PROCESS MAPPING
 * ============================================================
 */

function mapProcess(
  item: any
): ProcessItem {

  const data =
    item?.data || {};


  return {

    pid:
      item?.pid ??
      0,

    name:
      item?.name ||
      item?.process ||
      'Unknown',

    executablePath:
      data.exe ||
      data.executable ||
      'Unavailable',

    user:
      data.username ||
      'Unknown',

    status:
      'NORMAL',

    createTime:
      item?.timestamp ||
      '--',

    threatScore:
      0,

    parentProcess:
      'Unavailable',

    userContext:
      data.username ||
      'Unknown',

    commandLine:
      'Unavailable',

  } as ProcessItem;
}


/*
 * ============================================================
 * FILE MAPPING
 * ============================================================
 */

function mapFile(
  item: any
): FileActivityItem {

  const data =
    item?.data || {};


  const eventType =
    item?.event_type ||
    'unknown';


  let operation =
    eventType
      .replace(
        'file_',
        ''
      )
      .toUpperCase();


  let threatLevel =
    'normal';


  if (
    item?.source ===
    'detection_engine'
  ) {
    threatLevel =
      'critical';
  }

  else if (
    eventType ===
    'file_deleted' ||
    eventType ===
    'file_renamed'
  ) {
    threatLevel =
      'suspicious';
  }


  return {

    id:
      `file-${Date.now()}-${Math.random()}`,

    time:
      formatTime(
        item?.timestamp
      ),

    path:
      data.path ||
      data.to ||
      data.from ||
      'Unknown',

    operation,

    process:
      item?.process ||
      'Unknown',

    pid:
      item?.pid ??
      0,

    entropy:
      data.entropy ??
      0,

    threatLevel:
      threatLevel as any,

    isHoneytoken:
      Boolean(
        data.honeypot ||
        data.honeytoken
      ),

  } as FileActivityItem;
}


/*
 * ============================================================
 * PROVIDER
 * ============================================================
 */

export const SocProvider:
  React.FC<{
    children: React.ReactNode
  }> = ({ children }) => {


  /*
   * ----------------------------------------------------------
   * NAVIGATION
   * ----------------------------------------------------------
   */

  const [
    activeTab,
    setActiveTab
  ] = useState<TabType>(
    'overview'
  );


  /*
   * ----------------------------------------------------------
   * LIVE DATA
   * ----------------------------------------------------------
   */

  const [
    events,
    setEvents
  ] = useState<SocEvent[]>(
    []
  );


  const [
    connections,
    setConnections
  ] = useState<
    NetworkConnection[]
  >([]);


  const [
    processes,
    setProcesses
  ] = useState<ProcessItem[]>(
    []
  );


  const [
    selectedProcess,
    setSelectedProcess
  ] = useState<
    ProcessItem | null
  >(null);


  const [
    fileActivities,
    setFileActivities
  ] = useState<
    FileActivityItem[]
  >([]);


  /*
   * ----------------------------------------------------------
   * SYSTEM STATUS
   * ----------------------------------------------------------
   *
   * Start in NORMAL / DRY-RUN.
   * Real values are filled from Flask.
   */

  const [
    systemStatus,
    setSystemStatus
  ] = useState<SystemStatus>({

    threatState:
      'normal',

    safeLabMode:
      true,

    hostIsolated:
      false,

    processSuspended:
      false,

    streamActive:
      true,

    eps:
      0,

    activeProcessesCount:
      0,

    suspiciousProcessesCount:
      0,

    criticalAlertsCount:
      0,

    confidence:
      0,

    uptimeSeconds:
      0,

  });


  /*
   * ----------------------------------------------------------
   * BEHAVIORAL TELEMETRY
   * ----------------------------------------------------------
   */

  const [
    behavioralTelemetry,
    setBehavioralTelemetry
  ] = useState<BehavioralTelemetry>({

    filesCreated:
      0,

    filesModified:
      0,

    filesDeleted:
      0,

    filesRenamed:
      0,

    networkConns:
      0,

    entropyAvg:
      0,

  });


  /*
   * ----------------------------------------------------------
   * ACTION LOGS
   * ----------------------------------------------------------
   */

  const [
    actionLogs,
    setActionLogs
  ] = useState<string[]>([]);


  /*
   * ----------------------------------------------------------
   * CLOCK
   * ----------------------------------------------------------
   */

  const [
    currentTimeString,
    setCurrentTimeString
  ] = useState<string>(
    '--:--:-- UTC'
  );


  /*
   * ==========================================================
   * FETCH REAL EVENTS
   * ==========================================================
   */

  const fetchEvents =
    useCallback(
      async () => {

        try {

          const response =
            await fetch(
              `${API_BASE}/api/events`,
              {
                cache: 'no-store',
              }
            );


          if (!response.ok) {
            throw new Error(
              `Events API returned ${response.status}`
            );
          }


          const data =
            await response.json();


          const rawEvents =
            Array.isArray(
              data.recent_events
            )
              ? data.recent_events
              : [];


          /*
           * Convert backend Common Events
           * into the UI's SocEvent contract.
           */

          const mappedEvents =
            rawEvents.map(
              (
                event: any,
                index: number
              ) =>
                mapEvent(
                  event,
                  index
                )
            );


          setEvents(
            mappedEvents
          );


          /*
           * Network
           */

          const rawNetwork =
            Array.isArray(
              data.network_events_list
            )
              ? data.network_events_list
              : [];


          setConnections(
            rawNetwork.map(
              (
                event: any,
                index: number
              ) =>
                mapNetwork(
                  event,
                  index
                )
            )
          );


          /*
           * File activity
           */

          const rawFiles =
            Array.isArray(
              data.file_events_list
            )
              ? data.file_events_list
              : [];


          setFileActivities(
            rawFiles.map(
              (
                event: any
              ) =>
                mapFile(
                  event
                )
            )
          );


          /*
           * Behavioral counters
           */

          const fileCount =
            Number(
              data.file_events || 0
            );


          const networkCount =
            Number(
              data.network_events || 0
            );


          const detectionCount =
            Number(
              data.alerts || 0
            );


          const modifications =
            rawFiles.filter(
              (event: any) =>
                event.event_type ===
                'file_modified'
            ).length;


          const deletions =
            rawFiles.filter(
              (event: any) =>
                event.event_type ===
                'file_deleted'
            ).length;


          const renames =
            rawFiles.filter(
              (event: any) =>
                event.event_type ===
                'file_renamed'
            ).length;


          const creations =
            rawFiles.filter(
              (event: any) =>
                event.event_type ===
                'file_created'
            ).length;


          setBehavioralTelemetry({

            filesCreated:
              creations,

            filesModified:
              modifications,

            filesDeleted:
              deletions,

            filesRenamed:
              renames,

            networkConns:
              networkCount,

            entropyAvg:
              0,

          });


          /*
           * Risk from backend.
           */

          const risk =
            data.risk ||
            'NORMAL';


          setSystemStatus(
            previous => ({

              ...previous,

              threatState:
                risk.toLowerCase() as any,

              safeLabMode:
                true,

              streamActive:
                true,

              criticalAlertsCount:
                detectionCount,

              eps:
                data.total_events ||
                0,

            })
          );


        } catch (error) {

          console.error(
            'SOC events API error:',
            error
          );

        }

      },
      []
    );


  /*
   * ==========================================================
   * FETCH REAL STATUS
   * ==========================================================
   */

 /*
 * ==========================================================
 * FETCH REAL STATUS
 * ==========================================================
 */

const fetchStatus =
  useCallback(
    async () => {

      try {

        const response =
          await fetch(
            `${API_BASE}/api/status`,
            {
              cache: 'no-store',
            }
          );

        if (!response.ok) {
          throw new Error(
            `Status API returned ${response.status}`
          );
        }

        const data =
          await response.json();

        /*
         * Backend is the single source of truth.
         *
         * Expected backend fields:
         *
         * risk_level
         * event_count
         * file_event_count
         * network_event_count
         * process_event_count
         * detection_event_count
         * monitoring
         * safe_lab_mode
         */

        const riskLevel =
          String(
            data.risk_level ||
            'NORMAL'
          ).toLowerCase();

        const totalEvents =
          Number(
            data.event_count || 0
          );

        const fileEvents =
          Number(
            data.file_event_count || 0
          );

        const networkEvents =
          Number(
            data.network_event_count || 0
          );

        const processEvents =
          Number(
            data.process_event_count || 0
          );

        const detectionEvents =
          Number(
            data.detection_event_count || 0
          );

        const monitoring =
          Boolean(
            data.monitoring ??
            true
          );

        const safeLabMode =
          Boolean(
            data.safe_lab_mode ??
            true
          );

        /*
         * Update system state directly from
         * the real backend values.
         */

        setSystemStatus(
          previous => ({

            ...previous,

            threatState:
              riskLevel as any,

            safeLabMode:

              safeLabMode,

            hostIsolated:
              false,

            processSuspended:
              false,

            streamActive:
              monitoring,

            eps:
              totalEvents,

            /*
             * Keep process count separate
             * from detection count.
             */

            activeProcessesCount:
              processEvents,

            suspiciousProcessesCount:
              detectionEvents,

            criticalAlertsCount:
              detectionEvents,

            confidence:
              riskLevel === 'critical'
                ? 99.6
                : riskLevel === 'high'
                  ? 85
                  : 0,

            uptimeSeconds:
              previous.uptimeSeconds,

          })
        );

        /*
         * Log the real backend state so
         * debugging is easy.
         */

        console.log(
          '[SOC STATUS]',
          {
            risk: riskLevel,
            totalEvents,
            fileEvents,
            networkEvents,
            processEvents,
            detectionEvents,
            monitoring,
            safeLabMode,
          }
        );

      } catch (error) {

        console.error(
          'SOC status API error:',
          error
        );

      }

    },
    []
  );


  /*
   * ==========================================================
   * FETCH REAL PROCESS DATA
   * ==========================================================
   */

  const fetchProcesses =
    useCallback(
      async () => {

        try {

          const response =
            await fetch(
              `${API_BASE}/api/processes`,
              {
                cache: 'no-store',
              }
            );


          if (!response.ok) {
            throw new Error(
              `Process API returned ${response.status}`
            );
          }


          const data =
            await response.json();


          const rawProcesses =
            Array.isArray(
              data.processes
            )
              ? data.processes
              : [];


          const mappedProcesses =
            rawProcesses.map(
              (
                item: any
              ) =>
                mapProcess(
                  item
                )
            );


          setProcesses(
            mappedProcesses
          );


          setSelectedProcess(
            previous => {

              if (!previous) {

                return (
                  mappedProcesses[0] ||
                  null
                );

              }


              return (
                mappedProcesses.find(
                  process =>
                    process.pid ===
                    previous.pid
                ) ||
                mappedProcesses[0] ||
                null
              );

            }
          );


        } catch (error) {

          console.error(
            'SOC process API error:',
            error
          );

        }

      },
      []
    );


  /*
   * ==========================================================
   * INITIAL + CONTINUOUS POLLING
   * ==========================================================
   */

  useEffect(() => {

    fetchEvents();
    fetchStatus();
    fetchProcesses();


    if (
      !systemStatus.streamActive
    ) {
      return;
    }


    const interval =
      window.setInterval(
        () => {

          fetchEvents();
          fetchStatus();
          fetchProcesses();

        },
        2000
      );


    return () =>
      window.clearInterval(
        interval
      );

  }, [
    fetchEvents,
    fetchStatus,
    fetchProcesses,
    systemStatus.streamActive,
  ]);


  /*
   * ==========================================================
   * REAL CLOCK
   * ==========================================================
   */

  useEffect(() => {

    const updateTime =
  () => {

    const now =
      new Date();

    const istTime =
      now.toLocaleTimeString(
        'en-IN',
        {
          timeZone: 'Asia/Kolkata',
          hour: '2-digit',
          minute: '2-digit',
          second: '2-digit',
          hour12: false,
        }
      );

    setCurrentTimeString(
      `${istTime} IST`
    );

  };
  
    updateTime();


    const interval =
      window.setInterval(
        updateTime,
        1000
      );


    return () =>
      window.clearInterval(
        interval
      );

  }, []);


  /*
   * ==========================================================
   * UI ACTIONS
   * ==========================================================
   *
   * IMPORTANT:
   * These actions remain SAFE.
   *
   * We do not execute arbitrary process kills,
   * network isolation, or destructive recovery from
   * the frontend.
   *
   * The project protection controllers remain the
   * authoritative backend layer.
   */


  const addEvent =
    useCallback(
      (
        event: Omit<
          SocEvent,
          'id'
        >
      ) => {

        const newEvent = {

          ...event,

          id:
            `ui-${Date.now()}`,

        } as SocEvent;


        setEvents(
          previous => [
            newEvent,
            ...previous,
          ]
        );

      },
      []
    );


  const clearEvents =
    useCallback(
      () => {

        /*
         * Only clears the local UI view.
         *
         * It does NOT delete events.jsonl.
         */

        setEvents([]);

      },
      []
    );


  const toggleStream =
    useCallback(
      () => {

        setSystemStatus(
          previous => ({

            ...previous,

            streamActive:
              !previous.streamActive,

          })
        );

      },
      []
    );


  const toggleSafeLabMode =
    useCallback(
      () => {

        setSystemStatus(
          previous => {

            const next =
              !previous.safeLabMode;


            const now =
              new Date()
                .toISOString()
                .substring(
                  11,
                  19
                );


            setActionLogs(
              logs => [

                `[${now}] Safe Lab Mode changed locally to: ${
                  next
                    ? 'ENABLED'
                    : 'DISABLED'
                }.`,

                `[${now}] Frontend does not directly arm system-wide protection.`,

                ...logs,

              ]
            );


            return {

              ...previous,

              safeLabMode:
                next,

            };

          }
        );

      },
      []
    );


  const triggerContainment =
    useCallback(
      () => {

        const now =
          new Date()
            .toISOString()
            .substring(
              11,
              19
            );


        setActionLogs(
          logs => [

            `[${now}] [DRY-RUN] Containment requested from SOC dashboard.`,

            `[${now}] Backend protection controller remains authoritative.`,

            ...logs,

          ]
        );

      },
      []
    );


  const restoreHost =
    useCallback(
      () => {

        const now =
          new Date()
            .toISOString()
            .substring(
              11,
              19
            );


        setActionLogs(
          logs => [

            `[${now}] [DRY-RUN] Host restoration requested from SOC dashboard.`,

            `[${now}] No direct system modification was performed.`,

            ...logs,

          ]
        );

      },
      []
    );


  const killProcess =
    useCallback(
      (pid: number) => {

        const now =
          new Date()
            .toISOString()
            .substring(
              11,
              19
            );


        setActionLogs(
          logs => [

            `[${now}] [DRY-RUN] Process action requested for PID ${pid}.`,

            `[${now}] Frontend did not terminate the process.`,

            ...logs,

          ]
        );

      },
      []
    );


  /*
   * ----------------------------------------------------------
   * SIMULATION BUTTON
   * ----------------------------------------------------------
   *
   * Deliberately disabled as a fake telemetry generator.
   * The real Safe Simulator is:
   *
   * simulator/safe_simulator.py
   */

  const simulateAttack =
    useCallback(
      () => {

        const now =
          new Date()
            .toISOString()
            .substring(
              11,
              19
            );


        setActionLogs(
          logs => [

            `[${now}] Safe simulation requested.`,

            `[${now}] Use simulator/safe_simulator.py to generate real lab telemetry.`,

            ...logs,

          ]
        );

      },
      []
    );


  const resetSimulation =
    useCallback(
      () => {

        const now =
          new Date()
            .toISOString()
            .substring(
              11,
              19
            );


        setActionLogs(
          logs => [

            `[${now}] UI simulation state reset.`,

            `[${now}] Persistent telemetry was not deleted.`,

            ...logs,

          ]
        );


        fetchEvents();
        fetchStatus();
        fetchProcesses();

      },
      [
        fetchEvents,
        fetchStatus,
        fetchProcesses,
      ]
    );


  /*
   * ==========================================================
   * PROVIDER
   * ==========================================================
   */

  return (

    <SocContext.Provider
      value={{

        activeTab,

        setActiveTab,

        systemStatus,

        setSystemStatus,

        events,

        addEvent,

        clearEvents,

        toggleStream,

        connections,

        processes,

        selectedProcess,

        setSelectedProcess,

        fileActivities,

        behavioralTelemetry,

        actionLogs,

        triggerContainment,

        restoreHost,

        killProcess,

        toggleSafeLabMode,

        simulateAttack,

        resetSimulation,

        currentTimeString,

      }}
    >

      {children}

    </SocContext.Provider>

  );
};


/*
 * ============================================================
 * HOOK
 * ============================================================
 */

export const useSoc =
  () => {

    const context =
      useContext(
        SocContext
      );


    if (!context) {

      throw new Error(
        'useSoc must be used within a SocProvider'
      );

    }


    return context;

  };
